baseURL = "https://crossroadmonk.com"
languageCode = "en"
title = "The Crosssroad Monk"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
